Integrate vcpkg

diff --git a/.local/bin/scripts/= b/.local/bin/scripts/=
--- a/.local/bin/scripts/=
+++ b/.local/bin/scripts/=
@@ -1,11 +1,11 @@
-#!/usr/bin/env bash
+#!/usr/bin/env zsh
 
 # https://github.com/onespaceman/menu-calc
 # Calculator for use with rofi/dmenu(2)
 # Copying to the clipboard requires xclip
 
 usage() {
-    echo "    $(tput bold)menu calc$(tput sgr0)
+	echo "    $(tput bold)menu calc$(tput sgr0)
     A calculator for use with Rofi or dmenu(2)
     Basic usage:
     = 4+2
@@ -18,32 +18,32 @@ usage() {
 
     The expression may need quotation marks if
     launched outside of Rofi/dmenu"
-    exit
+	exit
 }
 
 case $1 in
-    -h|--help) usage ;;
+	-h | --help) usage ;;
 esac
 
 # Path to menu application
 if [[ -n $(command -v rofi) ]]; then
-    menu="$(command -v rofi) -dmenu"
+	menu="$(command -v rofi) -dmenu"
 elif [[ -n $(command -v dmenu) ]]; then
-    menu="$(command -v dmenu)"
+	menu="$(command -v dmenu)"
 else
-    echo >&2 "Rofi or dmenu not found"
-    exit
+	echo >&2 "Rofi or dmenu not found"
+	exit
 fi
 
 answer=$(echo "$@" | bc -l | sed '/\./ s/\.\{0,1\}0\{1,\}$//')
 
-action=$(echo -e "Copy to clipboard\nClear\nClose" |
-$menu -p "= $answer")
+action=$(echo -e "Copy to clipboard\nClear\nClose" \
+	| $menu -p "= $answer")
 
 case $action in
-    "Clear") $0 ;;
-    "Copy to clipboard") echo -n "$answer" | xclip ;;
-    "Close") ;;
-    "") ;;
-    *) $0 "$answer $action" ;;
+	"Clear") $0 ;;
+	"Copy to clipboard") echo -n "$answer" | xclip ;;
+	"Close") ;;
+	"") ;;
+	*) $0 "$answer $action" ;;
 esac
